title: "Mohammed Zabiullah C"
logo: images/logo.png
description: "Aspiring Machine Learning Engineer with a passion for innovation"
show_downloads: false
theme: jekyll-theme-minimal
color-scheme: dark
# remote_theme: "godalming123/minimal"
# plugins:
# - jekyll-remote-theme

# color-scheme: ["dark"]