title: "Mohammed Zabiullah C"
logo: images/logo1.png
description: "Aspiring Machine Learning Engineer with a passion for innovation"
show_downloads: false
# theme: jekyll-theme-minimal
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
color-scheme: dark
# remote_theme: "godalming123/minimal"
# plugins:
# - jekyll-remote-theme

# color-scheme: ["dark"]
