title: "Mohammed Zabiullah C"
logo: images/logo1.png
description: "Building with LLMs, agents, and ML models."
show_downloads: false
theme: jekyll-theme-minimal
color-scheme: dark

# remote_theme: "godalming123/minimal"
# plugins:
# - jekyll-remote-theme
