title: " "
logo: images/logo.png
description: ""
show_downloads: false
theme: jekyll-theme-minimal
color-scheme: auto-default-dark
# remote_theme: "godalming123/minimal"
# plugins:
# - jekyll-remote-theme

# color-scheme: ["dark"]